In [20]:
import numpy as np
import mpl_toolkits.axisartist.angle_helper as angle_helper
import matplotlib.cm as cmap
from matplotlib.projections import PolarAxes
from matplotlib.transforms import Affine2D
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt

from mpl_toolkits.axisartist import SubplotHost

from mpl_toolkits.axisartist import GridHelperCurveLinear

import astropy.units as u

from astropy.coordinates import Angle

from astropy.time import Time 

from astropy.visualization import quantity_support
quantity_support()

%matplotlib qt

In [50]:
def get_ra_matches_deg(matchfile, psr, plot=False):
    """Access right ascensions from a table of gaia matches in degrees

    From a table of Gaia matches, access the right ascensions for a given pulsar, either as astropy quantities
    to keep track of units, or if the table is for plotting, as dimensionless floats or ints so numpy accepts
    them.

    Args:
        matchfile (str): Full filename of the csv containing all the gaia matches for a list of pulsars,
            including all of their parameters as passed over from the output of get_matches().
        psr (str): Name of the pulsar being whose right ascensions should be accessed 
        plot (:obj:'bool', optional): Tells the function whether to record the quantities with or without 
            units depending on whether or not the table will be used to plot data

    Returns:
        Array: Array of right ascensions in the same order as the matches from the input file
    """

    f = open(matchfile, 'r')
    ras = []

    if plot:
        for line in f:
            values = line.split(',')
            if values[0] == psr:
                ras.append(float(values[7]))

        return ras
    else:
        for line in f:
            values = line.split(',')
            if values[0] == psr:
                ras.append(Angle(float(values[7]), u.deg))

        return ras  

def get_ra_matches_hms(matchfile, psr, plot=False): 
    """Access right ascensions from a table of gaia matches in hms 

    From a table of Gaia matches, access the right ascensions for a given pulsar, either as astropy quantities
    to keep track of units, or if the table is for plotting, as dimensionless floats or ints so numpy accepts
    them.

    Args:
        matchfile (str): Full filename of the csv containing all the gaia matches for a list of pulsars,
            including all of their parameters as passed over from the output of get_matches().
        psr (str): Name of the pulsar being whose right ascensions should be accessed 
        plot (:obj:'bool', optional): Tells the function whether to record the quantities with or without 
            units depending on whether or not the table will be used to plot data

    Returns:
        Array: Numpy array of right ascensions in the same order as the matches from the input file
    """
    f = open(matchfile, 'r')
    ras = []

    if plot:
        for line in f:
            values = line.split(',')
            if values[0] == psr:
                ras.append(float(values[7]))

        return np.array(ras)
    else:
        for line in f:
            values = line.split(',')
            if values[0] == psr:
                ras.append(Angle(float(values[7]), u.deg).hour)

        return np.array(ras)

In [56]:
def get_dec_matches_deg(matchfile, psr, plot=False):
    """Access declinations from a table of gaia matches in degrees 

    From a table of Gaia matches, access the declinations for a given pulsar, either as astropy quantities
    to keep track of units, or if the table is for plotting, as dimensionless floats or ints so numpy accepts
    them.

    Args:
        matchfile (str): Full filename of the csv containing all the gaia matches for a list of pulsars,
            including all of their parameters as passed over from the output of get_matches().
        psr (str): Name of the pulsar being whose declinations should be accessed 
        plot (:obj:'bool', optional): Tells the function whether to record the quantities with or without 
            units depending on whether or not the table will be used to plot data

    Returns:
        Array: Array of declinations in the same order as the matches from the input file
    """

    f = open(matchfile, 'r')
    decs = []

    if plot:
        for line in f:
            values = line.split(',')
            if values[0] == psr:
                decs.append(float(values[9]))

        return decs
    else:
        for line in f:
            values = line.split(',')
            if values[0] == psr:
                decs.append(Angle(float(values[9]), u.deg))

        return decs

def get_dec_matches_dms(matchfile, psr, plot=False):
    """Access declinations from a table of gaia matches in dms

    From a table of Gaia matches, access the declinations for a given pulsar, either as astropy quantities
    to keep track of units, or if the table is for plotting, as dimensionless floats or ints so numpy accepts
    them.

    Args:
        matchfile (str): Full filename of the csv containing all the gaia matches for a list of pulsars,
            including all of their parameters as passed over from the output of get_matches().
        psr (str): Name of the pulsar being whose declinations should be accessed 
        plot (:obj:'bool', optional): Tells the function whether to record the quantities with or without 
            units depending on whether or not the table will be used to plot data

    Returns:
        Array: Array of declinations in the same order as the matches from the input file
    """
    f = open(matchfile, 'r')
    decs = []

    if plot:
        for line in f:
            values = line.split(',')
            if values[0] == psr:
                decs.append(Angle(float(values[9]), u.deg).deg)
    #.to_string(unit=u.deg, sep=':')

        return np.array(decs)
    else:
        for line in f:
            values = line.split(',')
            if values[0] == psr:
                decs.append(Angle(float(values[9]), u.deg).dms)

        return np.array(decs)

In [57]:
def get_pmras(matchfile, psrname, plot=False):
    """Access proper motions in right ascension from a table of gaia matches

    Access a table of the proper motions of the gaia matches to a given pulsar from an output file of matches
    to a list of pulsars. Proper motions can either be given as astropy quantities with units of u.mas/u.yr, or as
    unitless quantities to be accepted by numpy for plotting.

    Args:
        matchfile (str): Full filename of the csv containing all the gaia matches for a list of pulsars,
            including all of their parameters as passed over from the output of get_matches().
        psr (str): Name of the pulsar being whose proper motions should be accessed 
        plot (:obj:'bool', optional): Tells the function whether to record the quantities with or without 
            units depending on whether or not the table will be used to plot data
    
    Returns:
        Array: Numpy array of proper motions in right ascension in the same order as the matches from 
            the input file
    """
    # all pms are in mas/yr
    f = open(matchfile, 'r')
    pmras = []

    if plot:
        for line in f:
            values = line.split(',')
            if values[0] == psrname:
                if values[14] == '':
                    pmras.append(0)
                else:
                    pmras.append(float(values[14]))

        return np.array(pmras)
    else:
        for line in f:
            values = line.split(',')
            if values[0] == psrname:
                if values[14] == '':
                    pmras.append(0*u.mas/u.yr)
                else:
                    pmras.append(float(values[14])*u.mas/u.yr)

        return np.array(pmras)


In [58]:
def get_pmdecs(matchfile, psrname, plot=False):
    """Access proper motions in declination from a table of gaia matches

    Access a table of the proper motions of the gaia matches to a given pulsar from an output file of matches
    to a list of pulsars. Proper motions can either be given as astropy quantities with units of mas/yr, or as
    unitless quantities to be accepted by numpy for plotting.

    Args:
        matchfile (str): Full filename of the csv containing all the gaia matches for a list of pulsars,
            including all of their parameters as passed over from the output of get_matches().
        psr (str): Name of the pulsar being whose proper motions should be accessed 
        plot (:obj:'bool', optional): Tells the function whether to record the quantities with or without 
            units depending on whether or not the table will be used to plot data
    
    Returns:
        Array: Numpy array of proper motions in declination in the same order as the matches from 
            the input file
    """
    # all pms are in mas/yr
    f = open(matchfile, 'r')
    pmdecs = []

    if plot:
        for line in f:
            values = line.split(',')
            if values[0] == psrname:
                if values[16] == '':
                    pmdecs.append(0)
                else:
                    pmdecs.append(float(values[16]))

        return np.array(pmdecs)
    else: # this part is going to throw an error having to do with numpy not liking quantities with units
        for line in f:
            values = line.split(',')
            if values[0] == psrname:
                if values[16] == '':
                    pmdecs.append(0*u.mas/u.yr)
                else:
                    pmdecs.append(float(values[16])*u.mas/u.yr)

        return np.array(pmdecs)

In [59]:
def get_distances(matchfile, psrname, plot=False):
    """Access distances from a table of gaia matches

    Access a table of the distances in Mpc of the gaia matches to a given pulsar from an output file of matches
    to a list of pulsars. Distances can either be given as astropy quantities with units of u.Mpc, or as
    unitless quantities to be accepted by numpy for plotting.

    Args:
        matchfile (str): Full filename of the csv containing all the gaia matches for a list of pulsars,
            including all of their parameters as passed over from the output of get_matches().
        psr (str): Name of the pulsar being whose distances should be accessed 
        plot (:obj:'bool', optional): Tells the function whether to record the quantities with or without 
            units depending on whether or not the table will be used to plot data
    
    Returns:
        Array: Array of distances in the same order as the matches from the input file
    """
    f = open(matchfile, 'r')
    dists = []

    if plot:
        for line in f:
            values = line.split(',')
            if values[0] == psrname:
                if values[11] == '':
                    dists.append(0)
                else:
                    dists.append(1/float(values[11])) # 1/parallax gives Mpc in this case as parallax is in mas
        return dists
    else:
        for line in f:
            values = line.split(',')
            if values[0] == psrname:
                if values[11] == '':
                    dists.append(0*u.Mpc)
                else:
                    dists.append(1/float(values[11])*u.Mpc) # 1/parallax gives Mpc in this case as parallax is in mas
        return dists

In [26]:
def curvelinear_test2(fig):
    """ 
    
    """

    global ax1

    tr = Affine2D().scale(np.pi/180., 1.) + PolarAxes.PolarTransform()

    extreme_finder = angle_helper.ExtremeFinderCycle(10, 60, 
                                                    lon_cycle= 360,
                                                    lat_cycle= None,
                                                    lon_minmax= None,
                                                    lat_minmax= (0, np.inf),
                                                    )
    
    grid_locator1 = angle_helper.LocatorHMS(12)
    tick_formatter1 = angle_helper.FormatterHMS()

    grid_locator2 = angle_helper.LocatorDMS(6)
    tick_formatter2 = angle_helper.FormatterDMS()

    grid_helper = GridHelperCurveLinear(tr,
                                        extreme_finder= extreme_finder,
                                        grid_locator1= grid_locator1,
                                        tick_formatter1= tick_formatter1,
                                        grid_locator2= grid_locator2,
                                        tick_formatter2= tick_formatter2)

    ax1 = SubplotHost(fig, 1, 1, 1, grid_helper= grid_helper)

    ax1.axis['right'].major_ticklabels.set_visible(True)
    ax1.axis['top'].major_ticklabels.set_visible(True)
    ax1.axis['bottom'].major_ticklabels.set_visible(True)

    ax1.axis['right'].get_helper().nth_coord_ticks=0
    ax1.axis['bottom'].get_helper().nth_coord_ticks=0

    fig.add_subplot(ax1)

    grid_helper = ax1.get_grid_helper()

    ax1.set_aspect(1.)
    ax1.set_xlim(-1,1)
    ax1.set_ylim(-1,1)

    ax1.set_xlabel('Right Ascension')
    ax1.set_ylabel('90$^\circ$ + Declination')
    ax1.grid(True)

    return tr

In [27]:
import matplotlib.pyplot as plt

fig = plt.figure(1,figsize= (5,5), constrained_layout=True)
plt.rcParams['axes.titley'] = 1.0
plt.rcParams['axes.titlepad'] = 25
fig.clf()

tr = curvelinear_test2(fig) # tr


decs = get_dec_matches_dms('testing_output.csv', 'J0024-7204Z', plot=True)
ras = get_ra_matches_hms('testing_output.csv', 'J0024-7204Z', plot=True)


# out_test = tr.transform(zip(ras, decs))
both = np.vstack((decs, ras))
out_test = tr.transform(both)

dist = get_distances('testing_output.csv', 'J0024-7204Z', plot=True)
print(dist)

cm = plt.cm.get_cmap('RdYlBu_r')
z = dist # for z to actually represent distances, write a function that gets
# distances for the matches in an array and set z to that, rather than random

with quantity_support():
    SC = ax1.scatter(out_test[:,0],
        out_test[:,1],
        c = z,
        cmap = cm,
        zorder = 9)

cbar = plt.colorbar(SC, shrink = 1., pad=0.2)
cbar.ax.tick_params(labelsize=8)
cbar.set_label('distance (Mpc)', fontsize=8)

plt.title('J0024-7204Z')
plt.show
plt.savefig('J0024-7204Z_equitorial_pos.pdf')

[1.3258032945301859, -1.6467227333323655, 1.4920682231033011, 1.1725721879627744, 3.9898715790447863, 5.512560631016167, -21.805204095200384, -3.501784427974687, 0, -0.7715547514944501, 0, 2.707743120388967, 0.7670890921278465, 1.2191589338415292, 1.4571419253305766, 11.656534371415047, -1.6844848746555365, -1.3093660566674359, 0, 0.5552115246923399, 18.42946429345029, 2.1595350855438626, 28.673242732759952, 1.8480975440509622, 0.7944546410534445, 7.489973287445592, -3.04846594204486, 1.580934584172246, 7.752007694285245, 7.60426905265399, 13.117928517948595, 0.8537445280235013, 0.28501483386724397, 0.694096523477555, 1.2840859696484423, 2.0523476569355714, 2.4711721466619783, 0.1274299397676152, 3.5796018327367976, 2.373714211118288, 4.106713585631808, 5.411381791279749, 1.907673272070561, -5.164981495167741, -97.48562380072929, 93.83463792733758, 1.7890834687849257, 0.8930310280475586, 1.41020645505057, 0.7792315246078799]


In [53]:
def plot_pos_eqt(inputfile, psrname, pmra=False, pmdec=False, dist=False):
    """Plots the positions of matches in polar coordinates.

    Plots in polar coordinates the positions of the gaia matches to a given pulsar. Specifying one of the 
    optional parameters to be true will add a colorbar of that parameter to the side of the graph, to show
    a thrid dimension of the parameters. One of the three optional boolean parameters must be set True for the 
    function to plot anything.

    Args:
        inputfile (str): Full filename of the csv file holding all the gaia matches that will be plotted. 
            Equivalent to the output file return from get_matches().
        psrname (str): Name of the pulsar for which we are plotting the match positions for comparison.
        pmra (:obj:'bool', optional): Also include a colorbar of the pmras for the given pulsar. Default 
            value is False.
        pmdec (:obj:'bool', optional): Also include a colorbar of the pmdecs for the given pulsar. Default 
            value is False.
        dist (:obj:'bool', optional): Also include a colorbar of the distances for the given pulsar. Default 
            value is False.
    """
    fig = plt.figure(1,figsize= (5,5), constrained_layout=True)
    plt.rcParams['axes.titley'] = 1.0
    plt.rcParams['axes.titlepad'] = 25
    fig.clf()

    tr = curvelinear_test2(fig) # tr

    decs = get_dec_matches_dms(inputfile, psrname, plot=True)
    ras = get_ra_matches_hms(inputfile, psrname, plot=True)

    print('raw ras data')
    print(ras)
    print('raw decs data')
    print(decs)
    

    # out_test = tr.transform(zip(ras, decs))
    both = np.vstack((decs, ras))
    out_test = tr.transform(both)

    print('values of out_test')
    print(out_test)
    print('ras that are being plotted:')
    print(out_test[:,0])
    print('decs that are being plotted:')
    print(out_test[:,1])

    if pmra:
        pmras = get_pmras(inputfile, psrname, plot=True)

        cm = plt.cm.get_cmap('RdYlBu_r')
        z = pmras
        name = 'pmra (mas/yr)'
        file = '_pmra'

    if pmdec:
        pmdecs = get_pmdecs(inputfile, psrname, plot=True)

        cm = plt.cm.get_cmap('RdYlBu_r')
        z = pmdecs
        name = '$\mu_{\delta}$ (mas/yr)'
        file = '_pmdec'

    if dist:
        dists = get_distances(inputfile, psrname, plot=True)

        cm = plt.cm.get_cmap('RdYlBu_r')
        z = dists
        name = 'distance (Mpc)'
        file = '_dist'

    with quantity_support():
        SC = ax1.scatter(ras, 
            decs,
            c = z,
            cmap = cm,
            zorder = 9)

            #out_test[:,0], out_test[:,1],

    cbar = plt.colorbar(SC, shrink = 1., pad=0.2)
    cbar.ax.tick_params(labelsize=8)
    cbar.set_label(name, fontsize=8)

    plt.title(psrname)
    plt.show
    plt.savefig(psrname + '_eqt_pos' + file + '.pdf')

In [55]:
plot_pos_eqt('cross_check.csv', 'J1012+5307', pmra=True)

raw ras data
[10.20527701 10.20540528 10.20598166 10.2012302  10.21411445 10.21703272]
raw decs data
[53.11577861 53.1189301  53.12198    53.11174411 53.12461156 53.10991773]
values of out_test
[[31.88198071 42.48717503]
 [31.87306952 42.48487733]
 [31.87002222 42.4848802 ]
 [10.04394856  1.80814661]
 [10.03981731  1.80753036]
 [10.05511272  1.81175766]]
ras that are being plotted:
[31.88198071 31.87306952 31.87002222 10.04394856 10.03981731 10.05511272]
decs that are being plotted:
[42.48717503 42.48487733 42.4848802   1.80814661  1.80753036  1.81175766]


In [34]:
get_pmdecs('actual_match.csv', 'J1816+4510', plot=True)

plot_pos_eqt('actual_match.csv', 'J1816+4510', pmdec=True)
# plot_pos_eqt('actual_match.csv', 'J1816+4510', pmdec=True)
# plot_pos_eqt('actual_match.csv', 'J1816+4510', dist=True)

[45.17453631 45.17181214 45.1714275  45.16981023]
[1.21814978 1.2182938  1.2185716  1.21888085]
[[3.18438460e+01 3.20384470e+01]
 [3.18441730e+01 3.20352993e+01]
 [1.21801846e+00 2.58998573e-02]
 [1.21860519e+00 2.59213092e-02]]


In [38]:
plot_pos_eqt('testing_output.csv', 'J0024-7204Z', pmra=True)

[-72.09167477 -72.08171972 -72.07764142 -72.07003904 -72.07340209
 -72.07216941 -72.07263432 -72.07075449 -72.10725907 -72.09664278
 -72.1076946  -72.05644835 -72.07944259 -72.1118226  -72.06197618
 -72.11047841 -72.07800005 -72.09570363 -72.1118075  -72.08250487
 -72.07836406 -72.04986841 -72.04913982 -72.11073425 -72.06915262
 -72.05588022 -72.04438857 -72.10961714 -72.05138098 -72.10684041
 -72.07234611 -72.12385278 -72.05969217 -72.09100601 -72.11629606
 -72.06487932 -72.04044245 -72.12675572 -72.12675078 -72.12700939
 -72.11544497 -72.12122235 -72.0380273  -72.12942088 -72.10698212
 -72.03753707 -72.05313481 -72.12822581 -72.04334735 -72.12984576]
[0.02724163 0.02362169 0.03001504 0.02446921 0.02985757 0.02386037
 0.03010333 0.02296218 0.02728353 0.02193907 0.02410984 0.02602901
 0.03272153 0.02674694 0.03068269 0.02458794 0.0333988  0.02040523
 0.03061204 0.01943368 0.03404479 0.02841859 0.02990794 0.02104675
 0.01905101 0.02090445 0.02573854 0.03330757 0.03177257 0.01976206
 0.0

In [60]:
def compare_pos_param_space(psr_name, ra, ra_err, dec, dec_err, pmra, pmra_err, pmdec, pmdec_err, pos_epoch, 
                            gaia_matches_filename):
    """Plots position parameter space for gaia matches of one pulsar in cartesian coordinates

    Plots the right ascension vs declination for all the matches of a given pulsar in cartesian coordinates, 
    just to see the comparison between the position of the pulsar and the identified matches in the parameter 
    space

    Args:
        psr_name (str): Name of the pulsar whose positions we are plotting and comparing to the position of 
            the pulsar.
        ra (str): Right ascension of the pulsar in hms exactly as it is in the input file of pulsars 
            from ATNF, as a string. (hms string separated by :)
        ra_err (float): Right ascension error of the pulsar as a float. (deg)
        dec (str): Declinations of the pulsar in hms exactlt as it is in the input file of pulsars 
            from ATNF, as a string. (hms string separated by :)
        dec_err (float): Declination error of the pulsar as a float. (deg)
        pmra (float): Proper motion in ra of the pulsar as a float (mas/yr)
        pmra_err (float): Proper motion in ra error of the pulsar as a float (mas/yr)
        pmdec (float): Proper motion in dec of the pulsar as a float (mas/yr)
        pmdec_err (float): Proper motion in dec of the pulsar as a float (mas/yr)
        pos_epoch (int): Epoch that the pulsar data was taken as an int (MJD)
        gaia_matches_filename (str): Full filename of the csv file that holds the gaia matches for a list of 
            pulsars, equivalent to the output of get_matches. This is the file that will be parsed to plot the
            positions of the matches 
    """
    fig1, ax1 = plt.subplots(figsize=(4,1)) 

    ra = ra 
    dec = dec 
    ra_err = ra_err*u.deg # must be floats
    dec_err = dec_err*u.deg # must be floats

    pmra = pmra*u.mas/u.yr
    pmra_err = pmra_err * u.mas / u.yr
    pmdec = pmdec * u.mas / u.yr
    pmdec_err = pmdec_err * u.mas / u.yr

    ra_ang = Angle(ra, u.deg)
    dec_ang = Angle(dec, u.deg)

    # this part is to plot the region within the propogated error after updating to the gaia epoch

    posepoch = pos_epoch

    p_epoch = Time(posepoch, format='mjd').jyear
    gaia_epoch = 2015.5 * u.yr
    year_diff = gaia_epoch - p_epoch.tolist() * u.yr

    bound1 = (ra_ang + ra_err) + ((pmra.to(u.deg/u.yr) + pmra_err.to(u.deg/u.yr))*year_diff) # right x err
    bound2 = (dec_ang + dec_err) + ((pmdec.to(u.deg/u.yr) + pmdec_err.to(u.deg/u.yr))*year_diff) # top y err

    bound3 = (ra_ang - ra_err) + ((pmra.to(u.deg/u.yr) - pmra_err.to(u.deg/u.yr))*year_diff) # left x err
    bound4 = (dec_ang - dec_err) + ((pmdec.to(u.deg/u.yr) - pmdec_err.to(u.deg/u.yr))*year_diff) # bottom y err
    bounds = [bound1, bound3, bound2, bound4]

    asym_err_x = [[bound3], [bound1]]
    asym_err_y = [[bound4], [bound2]]

    largest_err = 0
    for bound in bounds:
        if bound > largest_err:
            largest_err = bound 

    new_ra = ra_ang + (pmra.to(u.deg/u.yr)*year_diff)
    new_dec = dec_ang + (pmdec.to(u.deg/u.yr)*year_diff)

    region = plt.Circle((new_ra, new_dec), largest_err-new_ra, color='g', alpha=0.2)

    # plot the \mu in \alpha and \delta of the actual pulsar 
    with quantity_support():
        ax1.errorbar(ra_ang, dec_ang, dec_err, ra_err, 'bo') 
        ax1.plot(new_ra, new_dec, 'bo')
        ax1.add_patch(region)
    # plt.xlim([-1,2])
    # plt.ylim([-75,70])
    f = open(gaia_matches_filename, 'r')
    temp_zero = 0
    for line in f:
        values = line.split(',')
        if temp_zero == 0:
            temp_zero+=1
        elif values[0] == psr_name:
            # if float(values[8]) <= 0.1 and float(values[10]) <= 0.1:
                with quantity_support():
                    ax1.errorbar(float(values[7])*u.deg, float(values[9])*u.deg, float(values[8])*u.mas,
                    float(values[10])*u.mas, 'ro')
        else:
            break

    ax1.set_title('Angular offsets of Gaia matches from PSR' + psr_name, fontsize=16)
    ax1.set_xlabel(r'$\theta_{\alpha}$', fontsize=16)
    ax1.set_ylabel(r'$\theta_{\delta}$', fontsize=16)

    plt.xlim([ra_ang - 0.01*u.deg, ra_ang + 0.01*u.deg])
    plt.ylim([dec_ang - 0.01*u.deg, dec_ang + 0.01*u.deg])

    plt.tight_layout()

    plt.savefig(psr_name + 'pos_cartesian.pdf')

In [90]:
compare_pos_param_space('J1816+4510', '18:16:35.93436', 0.00007, '45:10:33.8618', 0.0004, 5.3, 0.8, -3., 1., 56047, 'actual_match.csv')

/tmp/ipykernel_2567/2527554705.py:77: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all axes decorations.
  plt.tight_layout()


In [29]:
def compare_pos_param_space2(inputfile, psrname, pmra=False, pmdec=False, dist=False): 
    """Plots position parameter space for gaia matches of one pulsar in a different way

    A second (and hopefully easier way) of plotting the right ascension versus declination of the gaia matches 
    to a given pulsar. This function can also allow the option of including a colorbar to show a third 
    parameter.

    Args:
        inputfile (str): Full filename of the csv file that holds all of the gaia matches and their 
            parameters. Equivalent to the output of get_matches()
        psrname (str): Name of the pulsar whose matches right ascensions vs. declinations are being plotted. 
        pmra (:obj:'bool', optional): Also include a colorbar of the pmras for the given pulsar. Default 
            value is False.
        pmdec (:obj:'bool', optional): Also include a colorbar of the pmdecs for the given pulsar. Default 
            value is False.
        dist (:obj:'bool', optional): Also include a colorbar of the distances for the given pulsar. Default 
            value is False.
    
    """
    fig = plt.figure(1,figsize= (3,3), constrained_layout=True)
    plt.rcParams['axes.titley'] = 1.0
    plt.rcParams['axes.titlepad'] = 25
    fig.clf()


    decs = get_dec_matches_dms(inputfile, psrname, plot=True)
    ras = get_ra_matches_hms(inputfile, psrname, plot=True)

    print(decs)
    print(ras)

    if pmra:
        pmras = get_pmras(inputfile, psrname, plot=True)

        cm = plt.cm.get_cmap('RdYlBu_r')
        z = pmras
        name = 'pmra (mas/yr)'
        file = '_pmra'

    if pmdec:
        pmdecs = get_pmdecs(inputfile, psrname, plot=True)

        cm = plt.cm.get_cmap('RdYlBu_r')
        z = pmdecs
        name = '$\mu_{\delta}$ (mas/yr)'
        file = '_pmdec'

    if dist:
        dists = get_distances(inputfile, psrname, plot=True)

        cm = plt.cm.get_cmap('RdYlBu_r')
        z = dists
        name = 'distance (Mpc)'
        file = '_dist'

    with quantity_support():
        plt.scatter(ras,
            decs,
            c = z,
            cmap = cm,
            zorder = 9)

    plt.xlim([np.amin(ras)-.01,np.amax(ras)+.01])
    plt.ylim([np.amin(decs)-.01,np.amax(decs)+.01])

    cbar = plt.colorbar(SC, shrink = 1., pad=0.2)
    cbar.ax.tick_params(labelsize=8)
    cbar.set_label(name, fontsize=8)

    plt.title(psrname)
    plt.show
    plt.savefig(psrname + '_cartesian_pos' + file + '.pdf')

In [112]:
compare_pos_param_space2('actual_match.csv', 'J1816+4510', pmra=True)

[45.17453631 45.17181214 45.1714275  45.16981023]
[1.21814978 1.2182938  1.2185716  1.21888085]


/tmp/ipykernel_2567/121501127.py:51: MatplotlibDeprecationWarning: Starting from Matplotlib 3.6, colorbar() will steal space from the mappable's axes, rather than from the current axes, to place the colorbar.  To silence this warning, explicitly pass the 'ax' argument to colorbar().
  cbar = plt.colorbar(SC, shrink = 1., pad=0.2)


In [30]:
compare_pos_param_space2('cross_check.csv', 'J1012+5307', pmra=True)

[53.11577861 53.1189301  53.12198    53.11174411 53.12461156 53.10991773]
[0.6803518  0.68036035 0.68039878 0.68008201 0.68094096 0.68113551]


/tmp/ipykernel_10286/121501127.py:51: MatplotlibDeprecationWarning: Starting from Matplotlib 3.6, colorbar() will steal space from the mappable's axes, rather than from the current axes, to place the colorbar.  To silence this warning, explicitly pass the 'ax' argument to colorbar().
  cbar = plt.colorbar(SC, shrink = 1., pad=0.2)


In [45]:
# get ra and dec arrays
ras = get_ra_matches_hms('actual_match.csv','J1816+4510', plot=True)
decs = get_dec_matches_dms('actual_match.csv','J1816+4510', plot=True)

print(ras)
print(decs)

pmras = get_pmras('actual_match.csv', 'J1816+4510', plot=True)

# convert ra from decimal degrees to radians -- will I want ras and decs to be in degrees?
ras = [x / 180.0 * np.pi for x in ras]

# actually make the plot
fig = plt.figure(figsize=(5,5))
gs = gridspec.GridSpec(4,2) # a grid layout to place subplots in a figure; I don't rlly understand it

# position plot in the figure using gridspec
ax = plt.subplot(gs[0], polar=True)
ax.set_ylim([90,30]) # this is dependent on the range of decs for the given psr matches

# set x, y ticks
angs = np.array([330., 345., 0., 15., 30., 45., 60.]) # angles in degrees 
plt.xticks(angs * np.pi / 180., fontsize= 8)
plt.yticks(np.arange(90,30,10), fontsize= 8)
ax.set_rlabel_position(120)
ax.set_xticklabels(['$22^h$', '$23^h$','$0^h$','$1^h$','$2^h$','$3^h$','$4^h$'], fontsize= 10)
ax.set_yticklabels(['$80^{\circ}$', '$70^{\circ}$', '$60^{\circ}$', '$50^{\circ}$', '$40^{\circ}$'])

cm = plt.cm.get_cmap('RdYlBu_r')

# Plot the points 
ax.scatter(ras, decs, c=pmras)

# Colorbar
cbar = plt.colorbar(SC, shrink=1., pad=0.05)
cbar.ax.tick_params(labelsize=8)
cbar.set_label('pmra (mas)', fontsize=8)






[1.21814978 1.2182938  1.2185716  1.21888085]
[45.17453631 45.17181214 45.1714275  45.16981023]


ValueError: The number of FixedLocator locations (0), usually from a call to set_ticks, does not match the number of ticklabels (5).

The X11 connection broke (error 1). Did the X11 server die?


: 